# Generated by Django 5.0 on 2025-05-27 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du lieu')),
                ('address', models.CharField(max_length=500, verbose_name='Adresse')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Lieu',
                'verbose_name_plural': 'Lieux',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_mode', models.CharField(choices=[('car', 'Voiture'), ('public', 'Transport Public'), ('walking', 'Marche'), ('bike', 'Vélo')], default='car', max_length=20, verbose_name='Mode de transport')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='routes.location', verbose_name='Départ')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='routes.location', verbose_name='Destination')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Demande de route',
                'verbose_name_plural': 'Demandes de routes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OptimizedRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_data', models.JSONField(verbose_name='Données de route')),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='Distance (km)')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Durée (min)')),
                ('cost_estimate', models.FloatField(blank=True, null=True, verbose_name='Coût estimé (FCFA)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('route_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='routes.routerequest', verbose_name='Demande de route')),
            ],
            options={
                'verbose_name': 'Route optimisée',
                'verbose_name_plural': 'Routes optimisées',
                'ordering': ['-created_at'],
            },
        ),
    ]
